[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000 # <-- Remplacé ici !
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false
# --- Destination : InfluxDB v1.8 ---
[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "orange_metrics"
  # Pas besoin d'authentification ici car INFLUXDB_HTTP_AUTH_ENABLED=false dans votre compose

# --- Collecte 1 : MariaDB ---
[[inputs.mysql]]
  servers = ["root:orangehrm@tcp(mariadb:3306)/?tls=false"]
  metric_version = 2

# --- Collecte 2 : Métriques Docker (CPU, RAM d'OrangeHRM & MariaDB) ---
[[inputs.docker]]
  endpoint = "tcp://host.docker.internal:2375"
  gather_services = false
  container_name_include = ["orangehrm_app", "orangehrm_db"] # Filtre sur vos conteneurs
  timeout = "5s"

# --- Collecte 3 : Santé HTTP d'OrangeHRM (Temps de réponse) ---
[[inputs.http_response]]
  urls = ["http://orangehrm:80"]
  response_timeout = "5s"
  method = "GET"
  follow_redirects = true