// Generated by Grafana k6 Studio (1.8.0) on 2026-03-21T16:56:59.749Z

import { group, sleep, check } from "k6";
import http from "k6/http";
import execution from "k6/execution";

export const options = {
  stages: [
    { target: 20, duration: "1m" },
    { target: 20, duration: "3m30s" },
    { target: 0, duration: "1m" },
  ],
};

export default function () {
  let params;
  let resp;
  let match;
  let regex;
  let url;
  const correlation_vars = {};

  group("Default group", function () {
    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        "Upgrade-Insecure-Requests": `1`,
        Accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 302": (r) => r.status === 302 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        "Upgrade-Insecure-Requests": `1`,
        Accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/auth/login`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        contentType: `application/json`,
        Referer: `http://172.19.48.1:8200/web/index.php/auth/login`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/core/i18n/messages`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        "Cache-Control": `max-age=0`,
        Origin: `http://172.19.48.1:8200`,
        "Content-Type": `application/x-www-form-urlencoded`,
        "Upgrade-Insecure-Requests": `1`,
        Accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        Referer: `http://172.19.48.1:8200/web/index.php/auth/login`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/auth/validate`;
    resp = http.request(
      "POST",
      url,
      JSON.parse(
        `{"_token":"b73b5e7f9a.SYuKJCRyc-fxxbabYUOWJoPbqHspOgAGwCPhdFX5yVA.Dv_HHUFDCqWkmoXxDQ34TNqN-RlPWWx-q3OzOAPLkAkF7_J-SjYnrpigxQ","username":"Admin","password":"Orangehrm$2026"}`,
      ),
      params,
    );

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        "Cache-Control": `max-age=0`,
        "If-None-Match": `"udPzp5tmK1qJ8SD5ih5TmI9iNvVEpV1lqd0luA2ddBE="`,
        contentType: `application/json`,
        Accept: `application/json`,
        Referer: `http://172.19.48.1:8200/web/index.php/dashboard/index`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/core/i18n/messages`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 304": (r) => r.status === 304 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        Referer: `http://172.19.48.1:8200/web/index.php/dashboard/index`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/buzz/feed?limit=5&offset=0&sortOrder=DESC&sortField=share.createdAtUtc`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        Origin: `http://172.19.48.1:8200`,
        Referer: `http://172.19.48.1:8200/web/index.php/dashboard/index`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/events/push`;
    resp = http.request("POST", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/dashboard/index`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/dashboard/employees/time-at-work?timezoneOffset=1&currentDate=2026-03-21&currentTime=17:53`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/dashboard/index`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/dashboard/employees/action-summary`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/dashboard/index`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/dashboard/shortcuts`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/dashboard/index`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/dashboard/employees/leaves?date=2026-03-21`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/dashboard/index`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/dashboard/employees/subunit`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/dashboard/index`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/dashboard/employees/locations`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        "Upgrade-Insecure-Requests": `1`,
        Accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        Referer: `http://172.19.48.1:8200/web/index.php/dashboard/index`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/pim/viewPimModule`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        "Cache-Control": `max-age=0`,
        "If-None-Match": `"udPzp5tmK1qJ8SD5ih5TmI9iNvVEpV1lqd0luA2ddBE="`,
        contentType: `application/json`,
        Accept: `application/json`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewEmployeeList`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/core/i18n/messages`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 304": (r) => r.status === 304 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewEmployeeList`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/pim/employees?limit=50&offset=0&model=detailed&includeEmployees=onlyCurrent&sortField=employee.firstName&sortOrder=ASC`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewEmployeeList`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/admin/employment-statuses?limit=0`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewEmployeeList`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/admin/job-titles?limit=0`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewEmployeeList`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/admin/subunits`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        "Upgrade-Insecure-Requests": `1`,
        Accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewEmployeeList`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/pim/addEmployee`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        "Cache-Control": `max-age=0`,
        "If-None-Match": `"udPzp5tmK1qJ8SD5ih5TmI9iNvVEpV1lqd0luA2ddBE="`,
        contentType: `application/json`,
        Accept: `application/json`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/addEmployee`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/core/i18n/messages`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 304": (r) => r.status === 304 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/addEmployee`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/pim/employees`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/addEmployee`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/core/validation/unique?value=123654&entityName=Employee&attributeName=employeeId`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/addEmployee`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/core/validation/unique?value=123654&entityName=Employee&attributeName=employeeId`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Content-Type": `application/json`,
        Origin: `http://172.19.48.1:8200`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/addEmployee`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/pim/employees`;
    resp = http.request(
      "POST",
      url,
      `{"firstName":"K6","middleName":"","lastName":"Training123654","empPicture":null,"employeeId":"123654"}`,
      params,
    );

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        "Upgrade-Insecure-Requests": `1`,
        Accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/addEmployee`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/pim/viewPersonalDetails/empNumber/2`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        "Cache-Control": `max-age=0`,
        "If-None-Match": `"udPzp5tmK1qJ8SD5ih5TmI9iNvVEpV1lqd0luA2ddBE="`,
        contentType: `application/json`,
        Accept: `application/json`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewPersonalDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/core/i18n/messages`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 304": (r) => r.status === 304 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewPersonalDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/pim/employees/2`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewPersonalDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/pim/employees/2/personal-details`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewPersonalDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/leave/workweek?model=indexed`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewPersonalDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/pim/employees/2/custom-fields?screen=personal`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewPersonalDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/pim/employees/2/screen/personal/attachments?limit=50&offset=0`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewPersonalDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/leave/holidays?fromDate=2026-01-01&toDate=2026-12-31`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewPersonalDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/pim/employees`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewPersonalDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/leave/workweek?model=indexed`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewPersonalDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/leave/holidays?fromDate=2026-01-01&toDate=2026-12-31`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        "Content-Type": `application/json`,
        Origin: `http://172.19.48.1:8200`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewPersonalDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/pim/employees/2/personal-details`;
    resp = http.request(
      "PUT",
      url,
      `{"lastName":"Training123654","firstName":"K6","middleName":"","employeeId":"123654","otherId":"","drivingLicenseNo":"","drivingLicenseExpiredDate":null,"gender":"1","maritalStatus":"Single","birthday":"1996-02-15","nationalityId":64}`,
      params,
    );

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        "Upgrade-Insecure-Requests": `1`,
        Accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewPersonalDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/pim/viewPimModule`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        "Cache-Control": `max-age=0`,
        "If-None-Match": `"udPzp5tmK1qJ8SD5ih5TmI9iNvVEpV1lqd0luA2ddBE="`,
        contentType: `application/json`,
        Accept: `application/json`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewEmployeeList`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/core/i18n/messages`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 304": (r) => r.status === 304 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewEmployeeList`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/admin/employment-statuses?limit=0`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewEmployeeList`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/pim/employees?limit=50&offset=0&model=detailed&includeEmployees=onlyCurrent&sortField=employee.firstName&sortOrder=ASC`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewEmployeeList`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/admin/job-titles?limit=0`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewEmployeeList`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/admin/subunits`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewEmployeeList`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/pim/employees?nameOrId=k6&includeEmployees=onlyCurrent`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewEmployeeList`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/pim/employees?limit=50&offset=0&model=detailed&nameOrId=k6&includeEmployees=onlyCurrent&sortField=employee.firstName&sortOrder=ASC`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        "Upgrade-Insecure-Requests": `1`,
        Accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewEmployeeList`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/pim/viewPersonalDetails/empNumber/2`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        "Cache-Control": `max-age=0`,
        "If-None-Match": `"udPzp5tmK1qJ8SD5ih5TmI9iNvVEpV1lqd0luA2ddBE="`,
        contentType: `application/json`,
        Accept: `application/json`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewPersonalDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/core/i18n/messages`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 304": (r) => r.status === 304 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewPersonalDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/pim/employees/2/personal-details`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewPersonalDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/pim/employees/2`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewPersonalDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/pim/employees/2/custom-fields?screen=personal`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewPersonalDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/leave/workweek?model=indexed`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewPersonalDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/pim/employees/2/screen/personal/attachments?limit=50&offset=0`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewPersonalDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/leave/holidays?fromDate=2026-01-01&toDate=2026-12-31`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewPersonalDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/pim/employees`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewPersonalDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/leave/workweek?model=indexed`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewPersonalDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/leave/holidays?fromDate=2026-01-01&toDate=2026-12-31`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        "Upgrade-Insecure-Requests": `1`,
        Accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewPersonalDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/pim/contactDetails/empNumber/2`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        "Cache-Control": `max-age=0`,
        "If-None-Match": `"udPzp5tmK1qJ8SD5ih5TmI9iNvVEpV1lqd0luA2ddBE="`,
        contentType: `application/json`,
        Accept: `application/json`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/contactDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/core/i18n/messages`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 304": (r) => r.status === 304 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/contactDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/pim/employee/2/contact-details`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/contactDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/pim/employees/2/custom-fields?screen=contact`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/contactDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/pim/employees/2`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/contactDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/pim/employees/2/screen/contact/attachments?limit=50&offset=0`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/contactDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/pim/employees/2/contact-details/validation/work-emails?workEmail=k6.training123654%40demo.test`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/contactDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/pim/employees/2/contact-details/validation/work-emails?workEmail=k6.training123654%40demo.test`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        "Content-Type": `application/json`,
        Origin: `http://172.19.48.1:8200`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/contactDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/pim/employee/2/contact-details`;
    resp = http.request(
      "PUT",
      url,
      `{"street1":"29 Rue des Sablons","street2":"","city":"Paris","province":"Paris","countryCode":"FR","zipCode":"75009","homeTelephone":"0111224455","workTelephone":null,"mobile":"0601020304","workEmail":"k6.training123654@demo.test","otherEmail":null}`,
      params,
    );

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        "Upgrade-Insecure-Requests": `1`,
        Accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/contactDetails/empNumber/2`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/pim/viewPimModule`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        "Cache-Control": `max-age=0`,
        "If-None-Match": `"udPzp5tmK1qJ8SD5ih5TmI9iNvVEpV1lqd0luA2ddBE="`,
        contentType: `application/json`,
        Accept: `application/json`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewEmployeeList`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/core/i18n/messages`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 304": (r) => r.status === 304 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewEmployeeList`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/pim/employees?limit=50&offset=0&model=detailed&includeEmployees=onlyCurrent&sortField=employee.firstName&sortOrder=ASC`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewEmployeeList`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/admin/employment-statuses?limit=0`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewEmployeeList`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/admin/job-titles?limit=0`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewEmployeeList`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/admin/subunits`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewEmployeeList`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/pim/employees?limit=50&offset=0&model=detailed&employeeId=123654&includeEmployees=onlyCurrent&sortField=employee.firstName&sortOrder=ASC`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        "Content-Type": `application/json`,
        Origin: `http://172.19.48.1:8200`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewEmployeeList`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/pim/employees`;
    resp = http.request("DELETE", url, `{"ids":[2]}`, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        Accept: `application/json`,
        "Cache-Control": `no-store, no-cache, must-revalidate, post-check=0, pre-check=0`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewEmployeeList`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/api/v2/pim/employees?limit=50&offset=0&model=detailed&employeeId=123654&includeEmployees=onlyCurrent&sortField=employee.firstName&sortOrder=ASC`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        "Upgrade-Insecure-Requests": `1`,
        Accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        Referer: `http://172.19.48.1:8200/web/index.php/pim/viewEmployeeList`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/auth/logout`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "Proxy-Connection": `keep-alive`,
        "Cache-Control": `max-age=0`,
        "If-None-Match": `"udPzp5tmK1qJ8SD5ih5TmI9iNvVEpV1lqd0luA2ddBE="`,
        contentType: `application/json`,
        Accept: `application/json`,
        Referer: `http://172.19.48.1:8200/web/index.php/auth/login`,
        "Accept-Encoding": `gzip, deflate`,
        "Accept-Language": `fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`,
      },
      cookies: {},
    };

    url = http.url`http://172.19.48.1:8200/web/index.php/core/i18n/messages`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 304": (r) => r.status === 304 });
  });
  sleep(1);
}
